[functions.run-sql]
enabled = true
verify_jwt = true
import_map = "./functions/run-sql/deno.json"
entrypoint = "./functions/run-sql/index.ts"

[functions.chatwoot-bot]
enabled = true
verify_jwt = false
entrypoint = "./functions/chatwoot-bot/index.ts"

[functions.whatsapp-bot]
enabled = true
verify_jwt = false
entrypoint = "./functions/whatsapp-bot/index.ts"

[functions.notificar-whatsapp]
enabled = true
verify_jwt = false
entrypoint = "./functions/notificar-whatsapp/index.ts"
